export const random = {
  data: {
    recipes: [
      {
        vegetarian: false,
        vegan: false,
        glutenFree: false,
        dairyFree: false,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        weightWatcherSmartPoints: 6,
        gaps: 'no',
        lowFodmap: false,
        aggregateLikes: 8,
        spoonacularScore: 27.0,
        healthScore: 2.0,
        creditsText:
          'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
        license: 'CC BY 3.0',
        sourceName: 'Foodista',
        pricePerServing: 33.23,
        extendedIngredients: [
          {
            id: 1011256,
            aisle: 'Milk, Eggs, Other Dairy',
            image: 'plain-yogurt.jpg',
            consistency: 'liquid',
            name: '0% fat greek yogurt',
            original: '1 cup Greek Non Fat Plain Yogurt',
            originalString: '1 cup Greek Non Fat Plain Yogurt',
            originalName: 'Greek Non Fat Plain Yogurt',
            amount: 1.0,
            unit: 'cup',
            meta: ['plain'],
            metaInformation: ['plain'],
            measures: {
              us: { amount: 1.0, unitShort: 'cup', unitLong: 'cup' },
              metric: {
                amount: 236.588,
                unitShort: 'ml',
                unitLong: 'milliliters',
              },
            },
          },
          {
            id: 18371,
            aisle: 'Baking',
            image: 'white-powder.jpg',
            consistency: 'solid',
            name: 'baking powder',
            original: '2 tsp. baking powder',
            originalString: '2 tsp. baking powder',
            originalName: 'baking powder',
            amount: 2.0,
            unit: 'tsp',
            meta: [],
            metaInformation: [],
            measures: {
              us: { amount: 2.0, unitShort: 'tsps', unitLong: 'teaspoons' },
              metric: { amount: 2.0, unitShort: 'tsps', unitLong: 'teaspoons' },
            },
          },
          {
            id: 18372,
            aisle: 'Baking',
            image: 'white-powder.jpg',
            consistency: 'solid',
            name: 'baking soda',
            original: '1/2 tsp. baking soda',
            originalString: '1/2 tsp. baking soda',
            originalName: 'baking soda',
            amount: 0.5,
            unit: 'tsp',
            meta: [],
            metaInformation: [],
            measures: {
              us: { amount: 0.5, unitShort: 'tsps', unitLong: 'teaspoons' },
              metric: { amount: 0.5, unitShort: 'tsps', unitLong: 'teaspoons' },
            },
          },
          {
            id: 1226,
            aisle: 'Health Foods;Baking;Milk, Eggs, Other Dairy',
            image: 'liquid-egg-substitute.jpg',
            consistency: 'solid',
            name: 'egg substitute',
            original: '2 eggs or egg substitute',
            originalString: '2 eggs or egg substitute',
            originalName: 'eggs or egg substitute',
            amount: 2.0,
            unit: '',
            meta: [],
            metaInformation: [],
            measures: {
              us: { amount: 2.0, unitShort: '', unitLong: '' },
              metric: { amount: 2.0, unitShort: '', unitLong: '' },
            },
          },
          {
            id: 19335,
            aisle: 'Baking',
            image: 'sugar-in-bowl.png',
            consistency: 'solid',
            name: 'granulated sugar',
            original: '1/2 cup plus 1 tbsp. granulated sugar',
            originalString: '1/2 cup plus 1 tbsp. granulated sugar',
            originalName: 'granulated sugar',
            amount: 0.5,
            unit: 'cup',
            meta: [],
            metaInformation: [],
            measures: {
              us: { amount: 0.5, unitShort: 'cups', unitLong: 'cups' },
              metric: {
                amount: 118.294,
                unitShort: 'ml',
                unitLong: 'milliliters',
              },
            },
          },
          {
            id: 12311111,
            aisle: 'Baking',
            image: 'lemon-oil.png',
            consistency: 'liquid',
            name: 'lemon extract',
            original: '1/4 tsp. lemon extract',
            originalString: '1/4 tsp. lemon extract',
            originalName: 'lemon extract',
            amount: 0.25,
            unit: 'tsp',
            meta: [],
            metaInformation: [],
            measures: {
              us: { amount: 0.25, unitShort: 'tsps', unitLong: 'teaspoons' },
              metric: {
                amount: 0.25,
                unitShort: 'tsps',
                unitLong: 'teaspoons',
              },
            },
          },
          {
            id: 9152,
            aisle: 'Produce',
            image: 'lemon-juice.jpg',
            consistency: 'liquid',
            name: 'lemon juice',
            original: '1 cup fresh lemon juice, about 12 lemons',
            originalString: '1 cup fresh lemon juice, about 12 lemons',
            originalName: 'fresh lemon juice, about 12 lemons',
            amount: 1.0,
            unit: 'cup',
            meta: ['fresh'],
            metaInformation: ['fresh'],
            measures: {
              us: { amount: 1.0, unitShort: 'cup', unitLong: 'cup' },
              metric: {
                amount: 236.588,
                unitShort: 'ml',
                unitLong: 'milliliters',
              },
            },
          },
          {
            id: 9156,
            aisle: 'Produce',
            image: 'zest-lemon.jpg',
            consistency: 'solid',
            name: 'lemon peel',
            original: '2 teaspoon lemon peel, grated (about 2 lemons)',
            originalString: '2 teaspoon lemon peel, grated (about 2 lemons)',
            originalName: 'lemon peel, grated (about 2 lemons)',
            amount: 2.0,
            unit: 'teaspoon',
            meta: ['grated', '( 2 lemons)'],
            metaInformation: ['grated', '( 2 lemons)'],
            measures: {
              us: { amount: 2.0, unitShort: 'tsps', unitLong: 'teaspoons' },
              metric: { amount: 2.0, unitShort: 'tsps', unitLong: 'teaspoons' },
            },
          },
          {
            id: 2047,
            aisle: 'Spices and Seasonings',
            image: 'salt.jpg',
            consistency: 'solid',
            name: 'salt',
            original: '1/4 teaspoon salt',
            originalString: '1/4 teaspoon salt',
            originalName: 'salt',
            amount: 0.25,
            unit: 'teaspoon',
            meta: [],
            metaInformation: [],
            measures: {
              us: { amount: 0.25, unitShort: 'tsps', unitLong: 'teaspoons' },
              metric: {
                amount: 0.25,
                unitShort: 'tsps',
                unitLong: 'teaspoons',
              },
            },
          },
          {
            id: 19335,
            aisle: 'Baking',
            image: 'sugar-in-bowl.png',
            consistency: 'solid',
            name: 'sugar',
            original: '1/2 pound sugar',
            originalString: '1/2 pound sugar',
            originalName: 'sugar',
            amount: 0.5,
            unit: 'pound',
            meta: [],
            metaInformation: [],
            measures: {
              us: { amount: 0.5, unitShort: 'lb', unitLong: 'pounds' },
              metric: { amount: 226.796, unitShort: 'g', unitLong: 'grams' },
            },
          },
          {
            id: 2050,
            aisle: 'Baking',
            image: 'vanilla-extract.jpg',
            consistency: 'liquid',
            name: 'vanilla extract',
            original: '1 tsp vanilla extract',
            originalString: '1 tsp vanilla extract',
            originalName: 'vanilla extract',
            amount: 1.0,
            unit: 'tsp',
            meta: [],
            metaInformation: [],
            measures: {
              us: { amount: 1.0, unitShort: 'tsp', unitLong: 'teaspoon' },
              metric: { amount: 1.0, unitShort: 'tsp', unitLong: 'teaspoon' },
            },
          },
          {
            id: 10020080,
            aisle: 'Baking',
            image: 'flour.png',
            consistency: 'solid',
            name: 'whole wheat pastry flour',
            original: '1 cup whole wheat pastry flour',
            originalString: '1 cup whole wheat pastry flour',
            originalName: 'whole wheat pastry flour',
            amount: 1.0,
            unit: 'cup',
            meta: ['whole wheat'],
            metaInformation: ['whole wheat'],
            measures: {
              us: { amount: 1.0, unitShort: 'cup', unitLong: 'cup' },
              metric: {
                amount: 236.588,
                unitShort: 'ml',
                unitLong: 'milliliters',
              },
            },
          },
        ],
        id: 649755,
        title: 'Lemon Quick Bread',
        readyInMinutes: 45,
        servings: 15,
        sourceUrl: 'http://www.foodista.com/recipe/3G7KLCH7/lemon-quick-bread',
        image: 'https://spoonacular.com/recipeImages/649755-556x370.jpg',
        imageType: 'jpg',
        summary:
          'You can never have too many morn meal recipes, so give Lemon Quick Bread a try. One serving contains <b>125 calories</b>, <b>2g of protein</b>, and <b>0g of fat</b>. For <b>31 cents per serving</b>, this recipe <b>covers 3%</b> of your daily requirements of vitamins and minerals. 8 people were impressed by this recipe. Head to the store and pick up greek non fat yogurt, baking powder, baking soda, and a few other things to make it today. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 29%</b>. This score is not so amazing. Try <a href="https://spoonacular.com/recipes/lemon-thyme-quick-bread-46688">Lemon Thyme Quick Bread</a>, <a href="https://spoonacular.com/recipes/lemon-cranberry-quick-bread-128143">Lemon-Cranberry Quick Bread</a>, and <a href="https://spoonacular.com/recipes/lemon-thyme-quick-bread-585933">Lemon-Thyme Quick Bread</a> for similar recipes.',
        cuisines: [],
        dishTypes: [],
        diets: [],
        occasions: [],
        instructions:
          '<ol><li>Preheat oven to 350</li><li>Beat yogurt, sugar, eggs, vanilla and lemon extract until blended</li><li>Stir together flour, lemon peel, baking powder, baking soda and salt. Add to yogurt mixture,mix just until blended. Spoon batter into a greased and floured 9- x 5-inch loaf pan or 3 mini loafs.</li><li>Bake for 50 minutes to 1 hour for 1 large loaf or 30  35 minutes for 3 mini loafs, or until a toothpick inserted into center comes out clean, shielding with aluminum foil after 50 minutes to prevent excessive browning.</li><li>To make glaze:</li><li>In a small sauce pan add sugar and lemon juice, stir until dissolved and clear. While the cake is still warm, pour the lemon-sugar mixture over the cake and allow it to soak in (a pastry brush works great for this, as does using a toothpick to make tiny holes that draw the syrup in better).</li><li>Cool in pan on a wire rack 10 minutes; remove from pan to wire rack. Then eat!!!!</li><li>Calories per slice:  111,  Fat:  .02,  Cholesterol:  0,  Sodium:  137,  Potassium:  32, Carbs:  23,  Fiber:  1.3,  Sugar:  10.3,  Protein:  3.9</li></ol>',
        analyzedInstructions: [
          {
            name: '',
            steps: [
              {
                number: 1,
                step:
                  'Preheat oven to 350Beat yogurt, sugar, eggs, vanilla and lemon extract until blended',
                ingredients: [
                  {
                    id: 12311111,
                    name: 'lemon extract',
                    localizedName: 'lemon extract',
                    image: 'lemon-oil.png',
                  },
                  {
                    id: 1052050,
                    name: 'vanilla',
                    localizedName: 'vanilla',
                    image: 'vanilla.jpg',
                  },
                  {
                    id: 1116,
                    name: 'yogurt',
                    localizedName: 'yogurt',
                    image: 'plain-yogurt.jpg',
                  },
                  {
                    id: 19335,
                    name: 'sugar',
                    localizedName: 'sugar',
                    image: 'sugar-in-bowl.png',
                  },
                  {
                    id: 1123,
                    name: 'egg',
                    localizedName: 'egg',
                    image: 'egg.png',
                  },
                ],
                equipment: [
                  {
                    id: 404784,
                    name: 'oven',
                    localizedName: 'oven',
                    image: 'oven.jpg',
                  },
                ],
              },
              {
                number: 2,
                step:
                  'Stir together flour, lemon peel, baking powder, baking soda and salt.',
                ingredients: [
                  {
                    id: 18369,
                    name: 'baking powder',
                    localizedName: 'baking powder',
                    image: 'white-powder.jpg',
                  },
                  {
                    id: 18372,
                    name: 'baking soda',
                    localizedName: 'baking soda',
                    image: 'white-powder.jpg',
                  },
                  {
                    id: 9156,
                    name: 'lemon peel',
                    localizedName: 'lemon peel',
                    image: 'zest-lemon.jpg',
                  },
                  {
                    id: 20081,
                    name: 'all purpose flour',
                    localizedName: 'all purpose flour',
                    image: 'flour.png',
                  },
                  {
                    id: 2047,
                    name: 'salt',
                    localizedName: 'salt',
                    image: 'salt.jpg',
                  },
                ],
                equipment: [],
              },
              {
                number: 3,
                step:
                  'Add to yogurt mixture,mix just until blended. Spoon batter into a greased and floured 9- x 5-inch loaf pan or 3 mini loafs.',
                ingredients: [
                  {
                    id: 1116,
                    name: 'yogurt',
                    localizedName: 'yogurt',
                    image: 'plain-yogurt.jpg',
                  },
                ],
                equipment: [
                  {
                    id: 404715,
                    name: 'loaf pan',
                    localizedName: 'loaf pan',
                    image: 'loaf-pan.png',
                  },
                ],
              },
              {
                number: 4,
                step:
                  'Bake for 50 minutes to 1 hour for 1 large loaf or 30  35 minutes for 3 mini loafs, or until a toothpick inserted into center comes out clean, shielding with aluminum foil after 50 minutes to prevent excessive browning.To make glaze:In a small sauce pan add sugar and lemon juice, stir until dissolved and clear. While the cake is still warm, pour the lemon-sugar mixture over the cake and allow it to soak in (a pastry brush works great for this, as does using a toothpick to make tiny holes that draw the syrup in better).Cool in pan on a wire rack 10 minutes; remove from pan to wire rack. Then eat!!!!Calories per slice:  111,  Fat:  .02,  Cholesterol:  0,  Sodium:  137,  Potassium:  32, Carbs:  23,  Fiber:  1.3,  Sugar:  10.3,  Protein:  3.9',
                ingredients: [
                  {
                    id: 9152,
                    name: 'lemon juice',
                    localizedName: 'lemon juice',
                    image: 'lemon-juice.jpg',
                  },
                  { id: 0, name: 'glaze', localizedName: 'glaze', image: '' },
                  {
                    id: 9150,
                    name: 'lemon',
                    localizedName: 'lemon',
                    image: 'lemon.png',
                  },
                  { id: 0, name: 'sauce', localizedName: 'sauce', image: '' },
                  {
                    id: 19335,
                    name: 'sugar',
                    localizedName: 'sugar',
                    image: 'sugar-in-bowl.png',
                  },
                  { id: 0, name: 'syrup', localizedName: 'syrup', image: '' },
                ],
                equipment: [
                  {
                    id: 404765,
                    name: 'aluminum foil',
                    localizedName: 'aluminum foil',
                    image: 'aluminum-foil.png',
                  },
                  {
                    id: 404764,
                    name: 'pastry brush',
                    localizedName: 'pastry brush',
                    image: 'pastry-brush.jpg',
                  },
                  {
                    id: 404669,
                    name: 'sauce pan',
                    localizedName: 'sauce pan',
                    image: 'sauce-pan.jpg',
                  },
                  {
                    id: 404644,
                    name: 'toothpicks',
                    localizedName: 'toothpicks',
                    image: 'toothpicks.jpg',
                  },
                  {
                    id: 405900,
                    name: 'wire rack',
                    localizedName: 'wire rack',
                    image: 'wire-rack.jpg',
                  },
                  {
                    id: 404784,
                    name: 'oven',
                    localizedName: 'oven',
                    image: 'oven.jpg',
                  },
                  {
                    id: 404645,
                    name: 'frying pan',
                    localizedName: 'frying pan',
                    image: 'pan.png',
                  },
                ],
                length: { number: 205, unit: 'minutes' },
              },
            ],
          },
        ],
        originalId: null,
        spoonacularSourceUrl:
          'https://spoonacular.com/lemon-quick-bread-649755',
      },
    ],
  },
};

export const recipe = {
  data: {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 24,
    gaps: 'no',
    lowFodmap: false,
    preparationMinutes: 5,
    cookingMinutes: 1,
    aggregateLikes: 1,
    spoonacularScore: 86.0,
    healthScore: 47.0,
    pricePerServing: 278.75,
    extendedIngredients: [
      {
        id: 98904,
        aisle: 'Canned and Jarred;Health Foods',
        image: 'chicken-broth.png',
        consistency: 'liquid',
        name: 'bone broth',
        original: '1/2 cup bone broth',
        originalString: '1/2 cup bone broth',
        originalName: 'bone broth',
        amount: 0.5,
        unit: 'cup',
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 0.5, unitShort: 'cups', unitLong: 'cups' },
          metric: { amount: 118.294, unitShort: 'ml', unitLong: 'milliliters' },
        },
      },
      {
        id: 10011109,
        aisle: 'Produce',
        image: 'coleslaw.png',
        consistency: 'solid',
        name: 'cole slaw mix',
        original:
          '1 bag pre-shredded cole slaw mix found in the produce section near the bagged salads',
        originalString:
          '1 bag pre-shredded cole slaw mix found in the produce section near the bagged salads',
        originalName:
          'pre-shredded cole slaw mix found in the produce section near the bagged salads',
        amount: 1.0,
        unit: 'bag',
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 1.0, unitShort: 'bag', unitLong: 'bag' },
          metric: { amount: 1.0, unitShort: 'bag', unitLong: 'bag' },
        },
      },
      {
        id: 18368,
        aisle: 'Ethnic Foods',
        image: 'puff-pastry-squares.jpg',
        consistency: 'solid',
        name: 'egg roll wrappers',
        original: '1 pkg egg roll wrappers cut into strips',
        originalString: '1 pkg egg roll wrappers cut into strips',
        originalName: 'egg roll wrappers cut into strips',
        amount: 1.0,
        unit: 'pkg',
        meta: ['cut into strips'],
        metaInformation: ['cut into strips'],
        measures: {
          us: { amount: 1.0, unitShort: 'pkg', unitLong: 'package' },
          metric: { amount: 1.0, unitShort: 'pkg', unitLong: 'package' },
        },
      },
      {
        id: 1022020,
        aisle: 'Spices and Seasonings',
        image: 'garlic-powder.png',
        consistency: 'solid',
        name: 'garlic powder',
        original: '1 tbsp garlic powder or to taste',
        originalString: '1 tbsp garlic powder or to taste',
        originalName: 'garlic powder or to taste',
        amount: 1.0,
        unit: 'tbsp',
        meta: ['to taste'],
        metaInformation: ['to taste'],
        measures: {
          us: { amount: 1.0, unitShort: 'Tbsp', unitLong: 'Tbsp' },
          metric: { amount: 1.0, unitShort: 'Tbsp', unitLong: 'Tbsp' },
        },
      },
      {
        id: 2021,
        aisle: 'Spices and Seasonings',
        image: 'ginger.png',
        consistency: 'solid',
        name: 'ground ginger',
        original: '1 tbsp ground ginger or to taste',
        originalString: '1 tbsp ground ginger or to taste',
        originalName: 'ground ginger or to taste',
        amount: 1.0,
        unit: 'tbsp',
        meta: ['to taste'],
        metaInformation: ['to taste'],
        measures: {
          us: { amount: 1.0, unitShort: 'Tbsp', unitLong: 'Tbsp' },
          metric: { amount: 1.0, unitShort: 'Tbsp', unitLong: 'Tbsp' },
        },
      },
      {
        id: 10219,
        aisle: 'Meat',
        image: 'meat-ground.jpg',
        consistency: 'solid',
        name: 'ground pork',
        original: '1 lb ground pork or any other meat you would like',
        originalString: '1 lb ground pork or any other meat you would like',
        originalName: 'ground pork or any other meat you would like',
        amount: 1.0,
        unit: 'lb',
        meta: ['or any other meat you would like'],
        metaInformation: ['or any other meat you would like'],
        measures: {
          us: { amount: 1.0, unitShort: 'lb', unitLong: 'pound' },
          metric: { amount: 453.592, unitShort: 'g', unitLong: 'grams' },
        },
      },
      {
        id: 4053,
        aisle: 'Oil, Vinegar, Salad Dressing',
        image: 'olive-oil.jpg',
        consistency: 'liquid',
        name: 'olive oil',
        original: 'vegetable or olive oil',
        originalString: 'vegetable or olive oil',
        originalName: 'vegetable or olive oil',
        amount: 4.0,
        unit: 'servings',
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 4.0, unitShort: 'servings', unitLong: 'servings' },
          metric: { amount: 4.0, unitShort: 'servings', unitLong: 'servings' },
        },
      },
      {
        id: 1002030,
        aisle: 'Spices and Seasonings',
        image: 'pepper.jpg',
        consistency: 'solid',
        name: 'pepper',
        original: '1/2 tsp pepper or to taste',
        originalString: '1/2 tsp pepper or to taste',
        originalName: 'pepper or to taste',
        amount: 0.5,
        unit: 'tsp',
        meta: ['to taste'],
        metaInformation: ['to taste'],
        measures: {
          us: { amount: 0.5, unitShort: 'tsps', unitLong: 'teaspoons' },
          metric: { amount: 0.5, unitShort: 'tsps', unitLong: 'teaspoons' },
        },
      },
      {
        id: 2047,
        aisle: 'Spices and Seasonings',
        image: 'salt.jpg',
        consistency: 'solid',
        name: 'salt',
        original: '1/ tsp salt or to taste',
        originalString: '1/ tsp salt or to taste',
        originalName: 'salt or to taste',
        amount: 1.0,
        unit: 'tsp',
        meta: ['to taste'],
        metaInformation: ['to taste'],
        measures: {
          us: { amount: 1.0, unitShort: 'tsp', unitLong: 'teaspoon' },
          metric: { amount: 1.0, unitShort: 'tsp', unitLong: 'teaspoon' },
        },
      },
      {
        id: 16124,
        aisle: 'Ethnic Foods;Condiments',
        image: 'soy-sauce.jpg',
        consistency: 'liquid',
        name: 'soy sauce',
        original: '1 tbsp soy sauce or to taste',
        originalString: '1 tbsp soy sauce or to taste',
        originalName: 'soy sauce or to taste',
        amount: 1.0,
        unit: 'tbsp',
        meta: ['to taste'],
        metaInformation: ['to taste'],
        measures: {
          us: { amount: 1.0, unitShort: 'Tbsp', unitLong: 'Tbsp' },
          metric: { amount: 1.0, unitShort: 'Tbsp', unitLong: 'Tbsp' },
        },
      },
    ],
    id: 1002030,
    title: 'Instant Pot Egg Roll Bowls',
    readyInMinutes: 6,
    servings: 4,
    sourceUrl:
      'https://www.idonthavetimeforthat.com/instant-pot-egg-roll-bowls/',
    image: 'https://spoonacular.com/recipeImages/1002030-556x370.jpg',
    imageType: 'jpg',
    summary:
      'Instant Pot Egg Roll Bowls is a Chinese recipe that serves 4. This main course has <b>797 calories</b>, <b>34g of protein</b>, and <b>40g of fat</b> per serving. For <b>$2.79 per serving</b>, this recipe <b>covers 34%</b> of your daily requirements of vitamins and minerals. This recipe is liked by 1 foodies and cooks. It is brought to you by idonthavetimeforthat.com. From preparation to the plate, this recipe takes roughly <b>6 minutes</b>. It is a good option if you\'re following a <b>dairy free</b> diet. Taking all factors into account, this recipe <b>earns a spoonacular score of 90%</b>, which is amazing. <a href="https://spoonacular.com/recipes/egg-roll-bowls-823792">Egg Roll Bowls</a>, <a href="https://spoonacular.com/recipes/instant-pot-burrito-bowls-974826">Instant Pot Burrito Bowls</a>, and <a href="https://spoonacular.com/recipes/instant-pot-korean-beef-bowls-983243">Instant Pot Korean Beef Bowls</a> are very similar to this recipe.',
    cuisines: ['Chinese', 'Asian'],
    dishTypes: [],
    diets: ['dairy free'],
    occasions: [],
    winePairing: {
      pairedWines: ['riesling', 'gewurztraminer', 'chenin blanc'],
      pairingText:
        'Riesling, Gewurztraminer, and Chenin Blanc are my top picks for Asian. The best wine for Asian food depends on the cuisine and dish - of course - but these acidic whites pair with a number of traditional meals, spicy or not. One wine you could try is Biltmore Estate Riesling. It has 4.7 out of 5 stars and a bottle costs about 13 dollars.',
      productMatches: [
        {
          id: 428467,
          title: 'Biltmore Estate Riesling',
          description:
            'Beautifully balanced with sweet apricot aromas, light honey flavors, and a crisp finish.',
          price: '$13.0',
          imageUrl: 'https://spoonacular.com/productImages/428467-312x231.jpg',
          averageRating: 0.9400000000000001,
          ratingCount: 4.0,
          score: 0.8630769230769231,
          link:
            'https://www.amazon.com/Biltmore-Estate-Riesling-750-mL/dp/B01FDZUPZG?tag=spoonacular-20',
        },
      ],
    },
    instructions:
      '<ol><li>Place Instant Pot on saute. Wait until it\'s hot and then add pork (or meat of choice). Add seasonings and soy sauce and brown meat. If you are using a lean meat (like ground pork or turkey) you will not need to drain it when its done. If you are using a higher fat meat (like ground beef) you will need to drain when browned.</li><li>When meat is browned, turn Instant Pot off and add the 1/2 cup <a href="https://www.idonthavetimeforthat.com/instant-pot-bone-broth/" target="_blank">bone broth</a>. Add bag of cole slaw mix on top and DO NOT stir. Place lid on and turn knob to sealing position.</li><li>Set Instant Pot on manual high pressure for 0 minutes. If you have a newer model Instant Pot, you select the pressure cook button instead for 0 minutes. And, yes 0 minutes is totally a thing. Just keep hitting the - button until the timer reaches 0.</li><li>When timer is up, preform a quick release. When pressure is released, open carefully and give everything a quick stir.</li><li>Spoon into bowls and enjoy!</li></ol>',
    analyzedInstructions: [
      {
        name: '',
        steps: [
          {
            number: 1,
            step:
              "Place Instant Pot on saute. Wait until it's hot and then add pork (or meat of choice).",
            ingredients: [
              {
                id: 1065062,
                name: 'meat',
                localizedName: 'meat',
                image: 'whole-chicken.jpg',
              },
              {
                id: 10010219,
                name: 'pork',
                localizedName: 'pork',
                image: 'pork-tenderloin-raw.png',
              },
            ],
            equipment: [
              {
                id: 414093,
                name: 'instant pot',
                localizedName: 'instant pot',
                image: '',
              },
            ],
          },
          {
            number: 2,
            step:
              'Add seasonings and soy sauce and brown meat. If you are using a lean meat (like ground pork or turkey) you will not need to drain it when its done. If you are using a higher fat meat (like ground beef) you will need to drain when browned.When meat is browned, turn Instant Pot off and add the 1/2 cup bone broth.',
            ingredients: [
              {
                id: 10023572,
                name: 'ground beef',
                localizedName: 'ground beef',
                image: 'fresh-ground-beef.jpg',
              },
              {
                id: 10219,
                name: 'ground pork',
                localizedName: 'ground pork',
                image: 'meat-ground.jpg',
              },
              {
                id: 98904,
                name: 'bone broth',
                localizedName: 'bone broth',
                image: 'chicken-broth.png',
              },
              {
                id: 1042027,
                name: 'seasoning',
                localizedName: 'seasoning',
                image: 'seasoning.png',
              },
              {
                id: 16124,
                name: 'soy sauce',
                localizedName: 'soy sauce',
                image: 'soy-sauce.jpg',
              },
              {
                id: 5165,
                name: 'whole turkey',
                localizedName: 'whole turkey',
                image: 'turkey-raw-whole.jpg',
              },
              {
                id: 1065062,
                name: 'meat',
                localizedName: 'meat',
                image: 'whole-chicken.jpg',
              },
            ],
            equipment: [
              {
                id: 414093,
                name: 'instant pot',
                localizedName: 'instant pot',
                image: '',
              },
            ],
          },
          {
            number: 3,
            step: 'Add bag of cole slaw mix on top and DO NOT stir.',
            ingredients: [
              {
                id: 10011109,
                name: 'coleslaw mix',
                localizedName: 'coleslaw mix',
                image: 'coleslaw.png',
              },
            ],
            equipment: [],
          },
          {
            number: 4,
            step:
              'Place lid on and turn knob to sealing position.Set Instant Pot on manual high pressure for 0 minutes. If you have a newer model Instant Pot, you select the pressure cook button instead for 0 minutes. And, yes 0 minutes is totally a thing. Just keep hitting the - button until the timer reaches 0.When timer is up, preform a quick release. When pressure is released, open carefully and give everything a quick stir.Spoon into bowls and enjoy!',
            ingredients: [],
            equipment: [
              {
                id: 414093,
                name: 'instant pot',
                localizedName: 'instant pot',
                image: '',
              },
              {
                id: 404783,
                name: 'bowl',
                localizedName: 'bowl',
                image: 'bowl.jpg',
              },
              {
                id: 404695,
                name: 'kitchen timer',
                localizedName: 'kitchen timer',
                image: 'kitchen-timer.jpg',
              },
            ],
            length: { number: 0, unit: 'minutes' },
          },
        ],
      },
    ],
    sourceName: null,
    creditsText: null,
    originalId: null,
  },
};
